openapi: 3.0.3
info:
  title: "Students Giftery API"
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
tags:
  - name: Subscriptions
security:
  - BasicAuth: []
paths:
  /subscriptions:
    post:
      security:
        - BasicAuth: []
      tags:
        - Subscriptions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: Successful
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
                example: wrong user name
        401:
          description: Authentication information is missing or invalid
          content:
            application/json:
              schema:
                type: string
                example: Authentication information is missing or invalid


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Subscription:
      type: string