GET http://localhost:8080/swagger-ui/index.html

###

POST http://localhost:8080/api/students-giftery/signUp/
Content-Type: application/json

{
  "firstName": "Daniil",
  "lastName": "Korotaev",
  "email": "daniil.korotaev@gmail.com",
  "password": "12345"
}

###

POST http://localhost:8080/api/students-giftery/signIn/
Content-Type: application/json

{
  "email": "daniil.korotaev@gmail.com",
  "password": "12345"
}

###

POST http://localhost:8080/api/students-giftery/createOrganization/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUwMTMwOTMwfQ.72XI2yxbJ4I0j3n9I6-x-iERua0BtlrczRY71KUO4jY

{
  "name": "Skuratov Сoffee",
  "description": "Coffee houses in 7 cities of Russia."
}

###

GET http://localhost:8080/api/students-giftery/organizations/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUwMTMwOTMwfQ.72XI2yxbJ4I0j3n9I6-x-iERua0BtlrczRY71KUO4jY

###

GET http://localhost:8080/api/students-giftery/accounts/getByOrganization?organizationId=2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUwMTMwOTMwfQ.72XI2yxbJ4I0j3n9I6-x-iERua0BtlrczRY71KUO4jY
